name: drote
description: "Draw and Note toghether"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^2.0.9
  file_saver: ^0.2.9
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1
  universal_html: ^2.2.4
  image_picker: ^1.0.4
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true
  assets:
    - assets/svgs/